// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/29/2026, 11:21:43 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/shangxb/fastapi-vue3/petct-hospital/petctw/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shangxb/fastapi-vue3/petct-hospital/petctw/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shangxb/fastapi-vue3/petct-hospital/petctw/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shangxb/fastapi-vue3/petct-hospital/petctw/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shangxb/fastapi-vue3/petct-hospital/petctw/plugins/**/*.{js,ts,mjs}","/Users/shangxb/fastapi-vue3/petct-hospital/petctw/composables/**/*.{js,ts,mjs}","/Users/shangxb/fastapi-vue3/petct-hospital/petctw/utils/**/*.{js,ts,mjs}","/Users/shangxb/fastapi-vue3/petct-hospital/petctw/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/shangxb/fastapi-vue3/petct-hospital/petctw/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/shangxb/fastapi-vue3/petct-hospital/petctw/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/shangxb/fastapi-vue3/petct-hospital/petctw/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;